In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [35]:
df = pd.read_csv('AB_NYC_2019.csv')
df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [36]:
df.shape

(48895, 16)

In [53]:
df = df.drop(['id','latitude','longitude','availability_365'],axis='columns')

In [54]:
df['price'].describe()

count    48895.000000
mean       152.720687
std        240.154170
min          0.000000
25%         69.000000
50%        106.000000
75%        175.000000
max      10000.000000
Name: price, dtype: float64

In [55]:
min_threshold, max_threshold = df['price'].quantile((0.05,0.98))
min_threshold,max_threshold

(40.0, 550.0)

In [56]:
df[df['price']<min_threshold]

,name,host_id,host_name,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count
36,Clean and Quiet in Brooklyn,7355,Vt,Brooklyn,Bedford-Stuyvesant,Private room,35,60,0,NaN,NaN,1
249,A SpeciaL!! Private Room in NY,303939,Lissette,Staten Island,Tompkinsville,Private room,36,2,193,2019-06-25,1.85,6
250,B NYC Staten Alternative...,303939,Lissette,Staten Island,Tompkinsville,Private room,37,2,147,2019-06-10,1.44,6
251,C Private Room By The Ferry,303939,Lissette,Staten Island,Tompkinsville,Private room,37,2,177,2019-07-02,1.71,6
256,D Private Che@p Room 2 Explore NYC,303939,Lissette,Staten Island,Tompkinsville,Private room,36,2,333,2019-07-02,3.19,6
258,Large and Cozy Private Bedroom,308652,Antonín,Brooklyn,Kensington,Private room,39,1,45,2019-05-16,0.46,2
397,SUPER BIG AND COZY PRIVATE BEDROOM,308652,Antonín,Brooklyn,Kensington,Private room,39,1,82,2019-05-19,0.94,2
469,Lady only Curtain-divided room,733894,Lucy,Queens,Sunnyside,Private room,33,44,31,2019-05-01,0.32,3
484,Affordable & Cozy,806214,Vanessa,Bronx,University Heights,Private room,37,4,117,2019-05-21,1.21,1
747,Bed-stuy Royal Room,1398639,Juliet,Brooklyn,Bedford-Stuyvesant,Private room,34,10,16,2019-03-27,0.19,3
776,Large Room in a Huge NY apartment.,1452026,Heidi,Queens,Astoria,Private room,30,5,3,2017-06-20,0.03,1
845,"HISTORIC WILLIAMSBURG, BKLYN #1",839679,Brady,Brooklyn,Williamsburg,Private room,30,3,24,2013-12-04,0.28,3
846,Inexpensive apartment in exchange for cat-care,997124,Alison,Brooklyn,Fort Greene,Private room,35,3,1,2018-05-13,0.07,1
957,Enjoy Staten Island Hospitality,1887999,Rimma & Jim,Staten Island,Graniteville,Private room,20,3,80,2019-05-26,0.92,1
1070,Lavender Joy Room in Duplex!,2219255,Natalie,Brooklyn,Canarsie,Private room,39,5,105,2019-06-09,1.21,3
1103,yahmanscrashpads,2321321,Lloyd,Queens,Jamaica,Shared room,39,1,454,2019-06-18,5.27,1
1167,Hi Traveler.. welcome,2459648,Ellen,Bronx,Allerton,Private room,35,7,2,2018-07-23,0.17,1
1237,lovely private room in South Park Slope,17985,Sing,Brooklyn,Sunset Park,Private room,36,10,5,2019-04-30,0.07,2
1387,Small Private Room # 1 with Window,2712353,Masud,Brooklyn,Cypress Hills,Private room,35,28,88,2019-05-22,1.05,4
1516,Cozy Private Bedroom $800 Month,1360296,Maria Daniela,Brooklyn,East New York,Private room,35,3,13,2019-05-29,0.16,1
1578,2 Beds/Queen & Full Beautiful Room 40 minsT.Sq...,3684360,Enrique,Bronx,Allerton,Private room,39,2,169,2019-06-12,2.07,4
1636,Tiffany Room in Duplex Home,2219255,Natalie,Brooklyn,Canarsie,Private room,39,5,60,2019-06-09,0.95,3
1665,Location Moreno,3250450,Petya,Queens,Long Island City,Private room,39,30,13,2015-12-13,0.16,18
1706,Nice beautiful room In the Bronx,3684360,Enrique,Bronx,Allerton,Private room,38,1,187,2019-06-23,2.34,4
1791,Washington Heights homestay,4112902,Tiffany,Manhattan,Washington Heights,Private room,36,1,33,2019-06-18,0.77,1
1830,Cozy room in beautiful apartment !,4298156,Melina,Manhattan,Harlem,Private room,35,7,0,NaN,NaN,1
1914,Queen-sized Room Avail in Huge 2 bdrm/2bth loft.,4414425,Ian,Brooklyn,Clinton Hill,Private room,36,1,8,2019-05-26,0.10,1
1965,Very Large Private Room on quiet st,4494343,Douglas,Bronx,Mount Eden,Private room,30,2,291,2019-06-20,3.69,1
2034,CHIC ROOM IN BROOKLYN BROWNSTONE,4847926,Shelley,Brooklyn,Flatbush,Private room,38,3,66,2019-06-10,0.93,3
2061,"Sunny, private room in Brooklyn!",4973668,Gloria,Brooklyn,Bedford-Stuyvesant,Private room,35,5,69,2019-06-15,0.91,3
...,...,...,...,...,...,...,...,...,...,...,...,...
48459,Nyc Beach Getaway(20 mins from airport),159382205,Rhonda,Queens,Arverne,Shared room,39,1,0,NaN,NaN,2
48486,"Cable and wfi, L/G included.",272872092,Chris,Queens,Forest Hills,Entire home/apt,16,9,1,2019-07-07,1.00,1
48488,"【Brooklyn N, R地铁口 45街阳光主卧7月短租】限女生,Only girls",122963021,莹,Brooklyn,Sunset Park,Private room,30,7,0,NaN,NaN,1
48514,Home Away From Home,159382205,Rhonda,Queens,Arverne,Shared room,37,1,0,NaN,NaN,2
48568,Nice and cozy apartment,35343897,Tatyanna,Brooklyn,Sheepshead Bay,Private room,38,12,0,NaN,NaN,1
48572,"Clinton Hill Oasis, Next To Subway/Citibike,",21261408,Jay,Brooklyn,Clinton Hill,Shared room,35,1,0,NaN,NaN,6
48575,Private Bedroom in Newly Renovated Apartment,273139430,Ethan,Brooklyn,Crown Heights,Private room,39,1,0,NaN,NaN,1
48589,Your family in NYC,259645305,Daniel,Brooklyn,Crown Heights,Private room,35,1,0,NaN,NaN,1
48629,Cozy Spacious Queens Private Room #1,273354185,Lee & Luffy,Bronx,Castle Hill,Private room,38,3,0,NaN,NaN,7
48630,Get Away NYC Queens Bedroom #2,273354185,Lee & Luffy,Bronx,Castle Hill,Private room,38,2,0,NaN,NaN,7
48631,NYC Traveler Get Away Private ROOM #3,273354185,Lee & Luffy,Bronx,Castle Hill,Private room,39,2,0,NaN,NaN,7
48632,Spacious brand new room getaway traveler NYC #4,273354185,Lee & Luffy,Bronx,Castle Hill,Private room,39,2,0,NaN,NaN,7
48633,Brand New Privated Room for NYC Traveler,273354185,Lee & Luffy,Bronx,Castle Hill,Private room,39,2,0,NaN,NaN,7
48636,2-MONTH SUBLEASE (WITH EARLY MOVE-IN),52984497,Friday,Brooklyn,Bedford-Stuyvesant,Private room,33,30,2,2019-07-06,2.00,1
48647,Cozy bedroom in diverse neighborhood near JFK,273393150,Liza,Queens,Richmond Hill,Private room,28,2,0,NaN,NaN,1
48665,Sunny Bedroom with renovated rooftop + balcony!,37872024,Jeano,Brooklyn,Crown Heights,Private room,30,10,0,NaN,NaN,1
48709,Cozy Nice Spot for ladies. Close to subway & Park,156114168,Kateryna,Brooklyn,Prospect-Lefferts Gardens,Shared room,39,1,0,NaN,NaN,6
48753,"Spacious Room w/ AC, Laundry, WiFi + Free Clea...",154980356,Joanne & Robert,Brooklyn,Bedford-Stuyvesant,Private room,32,30,0,NaN,NaN,1
48772,Bright & Cheerful! Modern w/ Laundry + Fast WiFi,107407045,Brett & Megan,Brooklyn,Bedford-Stuyvesant,Private room,35,30,0,NaN,NaN,1
48774,Laundry + Central AC - Modern Style - Near Metro,155298656,Brad & Rachel,Queens,Ridgewood,Private room,35,30,0,NaN,NaN,1
48808,Bright & Cheerful! Near Metro + Bars & Cafes,140961117,Christine & Ben,Manhattan,Harlem,Private room,39,30,0,NaN,NaN,1
48832,FLATBUSH HANG OUT AND GO,267223765,Jarmel,Brooklyn,Flatbush,Shared room,20,1,0,NaN,NaN,3
48845,Private 5 star room,261338177,Diana,Brooklyn,Gravesend,Private room,33,2,0,NaN,NaN,6
48846,#5 New Hotel-Like Private Room KING bed near JFK,263504959,David,Queens,Woodhaven,Private room,37,1,0,NaN,NaN,8
48847,#6 New Hotel-Like Private Room QUEEN Bed near JFK,263504959,David,Queens,Woodhaven,Private room,34,1,0,NaN,NaN,8
48851,#7 New Hotel-Like Private Room KING bed near JFK,263504959,David,Queens,Woodhaven,Private room,35,1,0,NaN,NaN,8
48852,"Cozy Private Room in Bushwick, Brooklyn",74162901,Christine,Brooklyn,Bushwick,Private room,30,1,1,2019-07-08,1.00,1
48867,The place you were dreaming for.(only for guys),261338177,Diana,Brooklyn,Gravesend,Shared room,25,1,0,NaN,NaN,6
48868,Heaven for you(only for guy),261338177,Diana,Brooklyn,Gravesend,Shared room,25,7,0,NaN,NaN,6
48871,A LARGE ROOM - 1 MONTH MINIMUM - WASHER&DRYER,144008701,Ozzy Ciao,Manhattan,Harlem,Private room,35,29,0,NaN,NaN,2

In [57]:
df[df['price']>max_threshold]

,name,host_id,host_name,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count
85,perfect for a family or small group,74303,Maggie,Brooklyn,Brooklyn Heights,Entire home/apt,800,1,25,2016-08-04,0.24,1
299,Unique spacious loft on the Bowery,281229,Alicia,Manhattan,Little Italy,Entire home/apt,575,2,191,2019-06-20,1.88,1
345,The Brooklyn Waverly,116599,Sahr,Brooklyn,Clinton Hill,Entire home/apt,650,5,0,NaN,NaN,3
365,2 BR w/ Terrace @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,Private room,599,3,9,2018-05-19,0.09,28
496,Luxury 2Bed/2.5Bath Central Park View,836168,Henry,Manhattan,Upper West Side,Entire home/apt,2000,30,30,2018-05-05,0.33,11
653,4 BEDROOM -2BATHRM WEST VILLAGE DUPLEX TOWNHOUSE,605463,West Village,Manhattan,West Village,Entire home/apt,700,3,131,2019-06-24,1.40,4
662,Heart & Soul of Greenwich Village,1314834,Rhona,Manhattan,Greenwich Village,Entire home/apt,850,3,107,2019-05-23,1.15,1
684,2 BR Duplex @ Box House Hotel,417504,The Box House Hotel,Brooklyn,Greenpoint,Private room,599,3,7,2018-11-16,0.08,28
691,Luxury Chelsea Townhouse at the High Line,1347034,Janine,Manhattan,Chelsea,Entire home/apt,760,2,7,2019-06-22,0.08,1
762,6 Bedroom Landmark West Village Townhouse,605463,West Village,Manhattan,West Village,Entire home/apt,1300,5,28,2018-09-25,0.31,4
780,#1 Yellow Block BnB/see at Net Flix Show Stay ...,1420300,Gordy,Brooklyn,Bedford-Stuyvesant,Entire home/apt,800,4,122,2019-07-02,1.37,1
946,Beautiful 3 bedroom in Manhattan,256239,Tracey,Manhattan,Upper West Side,Private room,3000,7,0,NaN,NaN,1
1105,$ (Phone number hidden by Airbnb) weeks - room f,2325861,Cynthia,Manhattan,Lower East Side,Private room,1300,1,0,NaN,NaN,1
1201,Your own townhouse in Bklyn Heights,2521513,Amy,Brooklyn,Brooklyn Heights,Entire home/apt,800,3,60,2019-01-01,0.70,1
1315,Bright and Spacious Manhattan,2834840,Sheri,Manhattan,Harlem,Private room,700,28,4,2016-10-03,0.05,1
1414,Luxury 1Bed with Central Park Views,836168,Henry,Manhattan,Upper West Side,Entire home/apt,1000,30,44,2015-09-28,0.53,11
1426,Sweet Super Bowl Accomodations,3198479,Gina,Manhattan,West Village,Entire home/apt,700,5,1,2012-09-18,0.01,1
1451,"Spacious, rare, elegant, art-filled loft w sauna",3272526,Lisa,Manhattan,SoHo,Entire home/apt,595,5,59,2019-06-27,0.77,1
1480,Lux 2Bed/2.5Bath Central Park Views,836168,Henry,Manhattan,Upper West Side,Entire home/apt,2000,30,59,2016-01-28,0.71,11
1553,UWS renovated 2bedroom 2bath near everything.,3606458,Mathew,Manhattan,Upper West Side,Entire home/apt,900,1,7,2019-01-01,0.09,2
1621,"Wedding guests accommodations, 3-7 bedrooms",1360198,Marina,Staten Island,Arrochar,Entire home/apt,625,4,1,2015-11-01,0.02,4
1650,Cozy 4 BR Brooklyn townhouse in Clinton Hill,3936154,Molly,Brooklyn,Clinton Hill,Entire home/apt,575,3,12,2019-07-01,0.15,1
1679,Gorgeous Duplex w Riverview Terrace,3315563,Mariko,Manhattan,Upper West Side,Entire home/apt,600,3,9,2018-10-20,0.12,2
1862,"Sunny, Family-Friendly 2 Bedroom",4289240,Lucy,Brooklyn,Prospect Heights,Entire home/apt,4000,4,0,NaN,NaN,1
1899,Spacious Centrally Located Apt!!!,3665164,Joseph,Manhattan,Chelsea,Private room,999,10,30,2016-10-12,0.40,1
1910,A Little Palace in Brooklyn for Shoots and Events,673406,Alex & Britta,Brooklyn,Bushwick,Entire home/apt,800,1,34,2019-07-01,0.45,1
2018,Architecturally Stunning Former Synagogue!,4751930,Martin,Manhattan,East Village,Entire home/apt,2500,30,15,2019-07-01,0.26,1
2040,"charming luxurious house, NY, Brooklyn",3343848,Laurence,Brooklyn,Park Slope,Entire home/apt,890,3,26,2018-11-27,0.34,1
2100,Elegant loft in heart of soho,5165749,Ben,Manhattan,SoHo,Entire home/apt,650,5,7,2014-06-27,0.09,2
2155,West Village Gem - Amazing Location,5466191,Ricky,Manhattan,West Village,Entire home/apt,950,3,28,2019-07-03,1.52,1
...,...,...,...,...,...,...,...,...,...,...,...,...
47694,Exquisite 3Br 2Ba Gem in UES,268623761,Julia & Todd,Manhattan,Upper East Side,Entire home/apt,600,3,0,NaN,NaN,1
47736,Luxury Hi-End Brooklyn Brownstone with backyard,269893009,Ek,Brooklyn,Bay Ridge,Entire home/apt,595,1,4,2019-07-07,4.00,1
47748,1 bedroom overlooking STONEWALL - PRIDE WEEKEND.,133372725,Andrew,Manhattan,West Village,Entire home/apt,750,1,0,NaN,NaN,1
47754,Splendid 4Br 2Ba | Steps From Midtown!,268452805,Marsha & Jakob,Manhattan,Kips Bay,Entire home/apt,600,3,0,NaN,NaN,1
47814,Sonder | 116 John | Polished Studio + Gym,219517861,Sonder (NYC),Manhattan,Financial District,Entire home/apt,699,29,0,NaN,NaN,327
47821,Sonder | 116 John | Simple Studio + Gym,219517861,Sonder (NYC),Manhattan,Financial District,Entire home/apt,699,29,0,NaN,NaN,327
47869,Private Townhome in Midtown East near UN,270294045,Christian,Manhattan,Midtown,Entire home/apt,1600,3,0,NaN,NaN,1
47870,Best Looking Townhouse in Brooklyn-GQ Magazine,5099333,Robert,Brooklyn,Fort Greene,Entire home/apt,800,3,0,NaN,NaN,1
47927,Penthouse Lofts + Private Terrace!,270590027,Amanda,Brooklyn,Williamsburg,Entire home/apt,599,2,1,2019-07-05,1.00,1
47950,★★ 4Br 2Ba Getaway in Chelsea ★★,268449136,Alexandra & William,Manhattan,Chelsea,Entire home/apt,800,3,1,2019-07-01,1.00,1
47995,GRAMERCY + WIGWAM = FUN!!!,270620369,Bryan,Manhattan,Midtown,Entire home/apt,650,3,0,NaN,NaN,1
48043,Luxury TriBeCa Apartment at an amazing price,271248669,Jenny,Manhattan,Tribeca,Entire home/apt,6500,180,0,NaN,NaN,1
48050,Chelsea Loft Living - Perfect for LARGE groups,63492343,Lenore,Manhattan,Chelsea,Entire home/apt,1050,2,0,NaN,NaN,1
48080,Luxury apartment 2 min to times square,203565865,Vinícius,Manhattan,SoHo,Entire home/apt,1308,2,0,NaN,NaN,1
48112,PRIVATE TIMES SQUARE TOWNHOUSE,269235140,Ronnie,Manhattan,Hell's Kitchen,Entire home/apt,560,1,0,NaN,NaN,1
48119,"Luxury Penthouse 3bed/2bath Apt w/Gym, Doorman",232596712,Jessica,Manhattan,Upper West Side,Entire home/apt,583,30,0,NaN,NaN,6
48184,Rare Find - 9bd/3ba Duplex - 15 mins to Manhattan,219908197,Anthony,Brooklyn,Williamsburg,Entire home/apt,595,2,0,NaN,NaN,3
48232,Veneta New York suite,266037277,Gianluigi,Manhattan,Hell's Kitchen,Private room,561,1,0,NaN,NaN,1
48282,VJ'S 5 HOUR YACHT TOUR,23732730,Buddy,Bronx,City Island,Entire home/apt,1000,1,0,NaN,NaN,4
48301,Private Bedroom in the Heart of Chelsea!,268920555,Terrence Jake,Manhattan,Chelsea,Private room,999,30,0,NaN,NaN,1
48304,Next to Times Square/Javits/MSG! Amazing 1BR!,270214015,Rogelio,Manhattan,Hell's Kitchen,Entire home/apt,2999,30,0,NaN,NaN,1
48305,2BR Near Museum Mile! Upper East Side!,272166348,Mary Rotsen,Manhattan,Upper East Side,Entire home/apt,1999,30,0,NaN,NaN,1
48310,ROMANTIC SUNSET YACHT CRUISE & FIREWORKS,23732730,Buddy,Bronx,City Island,Entire home/apt,600,1,0,NaN,NaN,4
48343,"Sunny, Spacious 2-bd Chelsea Apt",5723770,Olive,Manhattan,Chelsea,Entire home/apt,750,1,0,NaN,NaN,1
48378,Sunny SoHo Penthouse w/ Pvt. Terrace!,272485928,Michael,Manhattan,SoHo,Entire home/apt,600,3,0,NaN,NaN,1
48523,"Tasteful & Trendy Brooklyn Brownstone, near Train",217732163,Sandy,Brooklyn,Bedford-Stuyvesant,Entire home/apt,1369,1,0,NaN,NaN,1
48535,"Stunning & Stylish Brooklyn Luxury, near Train",245712163,Urvashi,Brooklyn,Bedford-Stuyvesant,Entire home/apt,1749,1,0,NaN,NaN,1
48697,HUGE LUXURY CONDO – INCREDIBLE WATER VIEWS,273619215,Layla,Manhattan,Upper West Side,Entire home/apt,750,4,0,NaN,NaN,1
48757,Luxury & Spacious 1500 ft² MANHATTAN Townhouse,11454384,Ellen,Manhattan,Tribeca,Entire home/apt,700,3,0,NaN,NaN,1
48839,Massage Spa. Stay overnight. Authors Artist dr...,274079964,Richard,Brooklyn,Sheepshead Bay,Private room,800,1,0,NaN,NaN,1

In [58]:
df2 = df[(df['price']>min_threshold) & (df['price']<max_threshold)]

In [59]:
df2.head()

,name,host_id,host_name,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count
0,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,Private room,149,1,9,2018-10-19,0.21,6
1,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,Entire home/apt,225,1,45,2019-05-21,0.38,2
2,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,Private room,150,3,0,NaN,NaN,1
3,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,Entire home/apt,89,1,270,2019-07-05,4.64,1
4,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,Entire home/apt,80,10,9,2018-11-19,0.10,1

In [60]:
df2.price.describe()

count    45096.000000
mean       138.083999
std         88.315198
min         41.000000
25%         75.000000
50%        110.000000
75%        175.000000
max        549.000000
Name: price, dtype: float64